### PR TITLE
Fix update method escapeUnescapedConfig

### LINKED ISSUE #611: escapeUnescapedConfig() update method is never run
Because its name doesn't start with `updateMethod`. It's also not unit tested. Looks like something I forgot to finish.

### PR DESCRIPTION
**Pull request by ArthurHoaro**
* Actually run it
  * unit tests

Fixes #611

### CODE REVIEW

File: application/Updater.php [hunk 1]
```diff
@@ -198,11 +198,11 @@ public function updateMethodConfigToJson()
      * Escape settings which have been manually escaped in every request in previous versions:
      *   - general.title
      *   - general.header_link
-     *   - extras.redirector
+     *   - redirector.url
      *
      * @return bool true if the update is successful, false otherwise.
      */
-    public function escapeUnescapedConfig()
+    public function updateMethodEscapeUnescapedConfig()
```
Comment (virtualtam) [inline application/Updater.php]: why the name change? :)

Comment (ArthurHoaro) [inline application/Updater.php]: Update methods have to start with `updateMethod` [to be run automatically](https://github.com/ArthurHoaro/Shaarli/blob/b9f8b83790a57b55f7d12471460537a268a24642/application/Updater.php#L78).
