### PR TITLE
Fix #773: set Piwik URL protocol

### LINKED ISSUE #773: Piwik URL does not support http:// or https://
Thx for adding Piwik as plugin - anyway I wondered why it did not work until I found in the source code that only www.domain.com/piwik is working and not if you provide http:// or https:// as prefix - I think this should be fixed or made clearer. 

Perhaps HTML 5 input type URL could be used for the form field - see more details at http://www.w3schools.com/html/html_form_input_types.asp

### PR DESCRIPTION
**Pull request by ArthurHoaro**

### CODE REVIEW

File: application/Updater.php [hunk 1]
```diff
@@ -363,6 +364,21 @@ public function updateMethodEscapeMarkdown()
...
+     *
+     * @return bool true if the update is successful, false otherwise.
+     */
+    public function updateMethodPiwikUrl()
+    {
+        if (! $this->conf->exists('plugins.PIWIK_URL') || startsWith($this->conf->get('plugins.PIWIK_URL'), 'http')) {
+            return true;
+        }
+
+        $this->conf->set('plugins.PIWIK_URL', 'http://'. $this->conf->get('plugins.PIWIK_URL'));
```
Comment (ArthurHoaro) [inline application/Updater.php]: $this->conf->write()
