### PR TITLE
Fix order of tags with the same number of occurrences

### LINKED ISSUE #1142: Tag sort is undefined for equal occurrences
Currently, `linksCountPerTag()` returns a list of tags sorted by their number of occurrences across links. 

They're sorted using [`arsort()`](https://secure.php.net/manual/en/function.arsort.php), which doesn't define the sort behaviour for equal values. This function doesn't produce the same result between PHP 5.6 and 7, hence the tests failure in #1141.

> **Note:**
> If two members compare as equal, their relative order in the sorted array is undefined.

Also [this comment](https://secure.php.net/manual/en/function.arsort.php#121205).

I suggest that we fix that by manually sorting equal tags by alphabetical order.

### PR DESCRIPTION
**Pull request by ArthurHoaro**
Fixes #1142

### CODE REVIEW

File: application/LinkDB.php [hunk 1]
```diff
@@ -458,8 +458,10 @@ public function linksCountPerTag($filteringTags = [], $visibility = 'all')
                 $tags[$caseMapping[strtolower($tag)]]++;
             }
         }
-        // Sort tags by usage (most used tag first)
-        arsort($tags);
+        $keys = array_keys($tags);
```
Comment (virtualtam) [inline application/LinkDB.php]: Would be worth testing and documenting for future reference (e.g. when we drop PHP 5.6 support)

Comment (ArthurHoaro) [reply application/LinkDB.php]: You're right, this method doesn't seem to be tested.
